### ISSUE TITLE
parallel cannot be defined if mpicasa is not installed 

### ISSUE THREAD

**Issue by SebaMarino** [jjtobin/auto_selfcal#36]
I'm trying out this for the first time on OSX mpicasa, so I tried casa -c auto_selfcal.py, which triggered some errors such as 

from casampi.MPIEnvironment import MPIEnvironment
ModuleNotFoundError: No module named 'casampi'

I had to manually comment the lines using casampia and define parallel=False. Perhaps this is something that could be improved in the future with a try/except statement.

**Comment by jjtobin** [comment]
Hi Seba,

Thanks for your feedback, indeed we've only been testing on Linux systems. I had overlooked the fact that Mac builds of CASA do not include MPI capability which resulted in your issue. I will put in an update with a try/except as you suggest.

**Comment by jjtobin** [comment]
I just added a commit with the try/except if you want to test it on Mac.

**Comment by SebaMarino** [comment]
Hi John,  thanks for the quick reply. I think run_selfcal.py also requires the same fix.

I also noticed that the readme file should also say that run_selfcal.py has to be copied to the working directory.

**Comment by jjtobin** [comment]
Thanks for pointing that out regarding run_selfcal.py!
